### ISSUE TITLE
Cant get historical metadata of a chain.

### ISSUE THREAD

**Issue by DragonDmoney** [Aphoh/go-substrate-gen#10]
When I'm trying use this on historical metadata of a chain, it does not work:

`error generating calls for pallet System: no call type found. Expected a path like *_runtime::RuntimeCall`

**How to reproduce:**

1. Get historical metadata (from block 10000000): `curl -L -X POST -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "state_getMetadata", "params": ["0x6c51377632106ddba379416f2ef5e24450e90cee8c78a70daa262b2ae6f27e93"]}' https://rpc.polkadot.io > polkadot-meta.json`
2. Run substrate-gen

*Note:* I've tried this on two chains already.

**Comment by naterarmstrong** [comment]
That is expected behavior right now, unfortunately.

As of polkadot v0.9.30, they changed the namings of `Origin` -> `RuntimeOrigin`, `Event` -> `RuntimeEvent`, `Call` -> `RuntimeCall`. As this code generation specifically looks for the `Call`/`RuntimeCall` type by name, it now fails on old chains that still use versions before 0.9.30.

This was changed in #5. `go-substrate-gen` version 0.6.0 should work for those old chains. Alternately, if there are changes since then you want to use, it is literally 1 line of code.

**Comment by DragonDmoney** [comment]
You're a fucking chad
